package ferro.model;
// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApscEstProdXPed generated by hbm2java
 */
@Entity
@Table(name="APSC_EST_PROD_X_PED"
,schema="ERP"
/*"dbo"
,catalog="ERP"*/
)
public class ApscEstProdXPed  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idEstProdPed;
     private ApscEstProdDesc apscEstProdDesc;
     private ApscPedidoDet apscPedidoDet;
     private String idProd;
     private String descripcion;
     private String usuMod;
     private String usuReg;
     private Date fecReg;
     private Date fecMod;
     private Boolean estado;

    public ApscEstProdXPed() {
    }

	
    public ApscEstProdXPed(long idEstProdPed) {
        this.idEstProdPed = idEstProdPed;
    }
    public ApscEstProdXPed(long idEstProdPed, ApscEstProdDesc apscEstProdDesc, ApscPedidoDet apscPedidoDet, String idProd, String descripcion, String usuMod, String usuReg, Date fecReg, Date fecMod, Boolean estado) {
       this.idEstProdPed = idEstProdPed;
       this.apscEstProdDesc = apscEstProdDesc;
       this.apscPedidoDet = apscPedidoDet;
       this.idProd = idProd;
       this.descripcion = descripcion;
       this.usuMod = usuMod;
       this.usuReg = usuReg;
       this.fecReg = fecReg;
       this.fecMod = fecMod;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="ID_EST_PROD_PED", unique=true, nullable=false)
    public long getIdEstProdPed() {
        return this.idEstProdPed;
    }
    
    public void setIdEstProdPed(long idEstProdPed) {
        this.idEstProdPed = idEstProdPed;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EST_PROD_DESC")
    public ApscEstProdDesc getApscEstProdDesc() {
        return this.apscEstProdDesc;
    }
    
    public void setApscEstProdDesc(ApscEstProdDesc apscEstProdDesc) {
        this.apscEstProdDesc = apscEstProdDesc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PED_DET")
    public ApscPedidoDet getApscPedidoDet() {
        return this.apscPedidoDet;
    }
    
    public void setApscPedidoDet(ApscPedidoDet apscPedidoDet) {
        this.apscPedidoDet = apscPedidoDet;
    }

    
    @Column(name="ID_PROD", length=16)
    public String getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(String idProd) {
        this.idProd = idProd;
    }

    
    @Column(name="DESCRIPCION", length=1024)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="USU_MOD", length=16)
    public String getUsuMod() {
        return this.usuMod;
    }
    
    public void setUsuMod(String usuMod) {
        this.usuMod = usuMod;
    }

    
    @Column(name="USU_REG", length=16)
    public String getUsuReg() {
        return this.usuReg;
    }
    
    public void setUsuReg(String usuReg) {
        this.usuReg = usuReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_REG", length=23)
    public Date getFecReg() {
        return this.fecReg;
    }
    
    public void setFecReg(Date fecReg) {
        this.fecReg = fecReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_MOD", length=23)
    public Date getFecMod() {
        return this.fecMod;
    }
    
    public void setFecMod(Date fecMod) {
        this.fecMod = fecMod;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


