package ferro.model;

// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApscEstProdDesc generated by hbm2java
 */
@Entity
@Table(name = "APSC_EST_PROD_DESC",schema="ERP"
/*"dbo"
,catalog="ERP"*/)
public class ApscEstProdDesc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idEstProdDesc;
	private String codEst;
	private String descripcion;
	private Date fecReg;
	private Date fecMod;
	private String usuReg;
	private String usuMod;
	private Boolean estado;
	private Set<ApscEstProdXPed> apscEstProdXPeds = new HashSet<ApscEstProdXPed>(0);

	public ApscEstProdDesc() {
	}

	public ApscEstProdDesc(long idEstProdDesc) {
		this.idEstProdDesc = idEstProdDesc;
	}

	public ApscEstProdDesc(long idEstProdDesc, String codEst,
			String descripcion, Date fecReg, Date fecMod, String usuReg,
			String usuMod, Boolean estado, Set<ApscEstProdXPed> apscEstProdXPeds) {
		this.idEstProdDesc = idEstProdDesc;
		this.codEst = codEst;
		this.descripcion = descripcion;
		this.fecReg = fecReg;
		this.fecMod = fecMod;
		this.usuReg = usuReg;
		this.usuMod = usuMod;
		this.estado = estado;
		this.apscEstProdXPeds = apscEstProdXPeds;
	}

	@Id
	@Column(name = "ID_EST_PROD_DESC", unique = true, nullable = false)
	public long getIdEstProdDesc() {
		return this.idEstProdDesc;
	}

	public void setIdEstProdDesc(long idEstProdDesc) {
		this.idEstProdDesc = idEstProdDesc;
	}

	@Column(name = "COD_EST", length = 16)
	public String getCodEst() {
		return this.codEst;
	}

	public void setCodEst(String codEst) {
		this.codEst = codEst;
	}

	@Column(name = "DESCRIPCION", length = 64)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REG", length = 23)
	public Date getFecReg() {
		return this.fecReg;
	}

	public void setFecReg(Date fecReg) {
		this.fecReg = fecReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MOD", length = 23)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "USU_REG", length = 16)
	public String getUsuReg() {
		return this.usuReg;
	}

	public void setUsuReg(String usuReg) {
		this.usuReg = usuReg;
	}

	@Column(name = "USU_MOD", length = 16)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apscEstProdDesc")
	public Set<ApscEstProdXPed> getApscEstProdXPeds() {
		return this.apscEstProdXPeds;
	}

	public void setApscEstProdXPeds(Set<ApscEstProdXPed> apscEstProdXPeds) {
		this.apscEstProdXPeds = apscEstProdXPeds;
	}

}
