package ferro.model;
// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApscCotizacion generated by hbm2java
 */
@Entity
@Table(name="APSC_COTIZACION"
,schema="ERP"
/*"dbo"
,catalog="ERP"*/
)
public class ApscCotizacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idCotizacion;
     private Long idCliente;
     private Long idForpago;
     private Long idVend;
     private Long idEstado;
     private String anio;
     private String periodo;
     private String cdPed;
     private String regCont;
     private String cdOp;
     private BigDecimal bimNeto;
     private BigDecimal igv;
     private BigDecimal total;
     private Date fecReg;
     private Date fecMod;
     private String usuReg;
     private String usuMod;
     private Boolean estado;
     private Set<ApscCotizacionDet> apscCotizacionDets = new HashSet<ApscCotizacionDet>(0);

    public ApscCotizacion() {
    }

	
    public ApscCotizacion(long idCotizacion) {
        this.idCotizacion = idCotizacion;
    }
    public ApscCotizacion(long idCotizacion, Long idCliente, Long idForpago, Long idVend, Long idEstado, String anio, String periodo, String cdPed, String regCont, String cdOp, BigDecimal bimNeto, BigDecimal igv, BigDecimal total, Date fecReg, Date fecMod, String usuReg, String usuMod, Boolean estado, Set<ApscCotizacionDet> apscCotizacionDets) {
       this.idCotizacion = idCotizacion;
       this.idCliente = idCliente;
       this.idForpago = idForpago;
       this.idVend = idVend;
       this.idEstado = idEstado;
       this.anio = anio;
       this.periodo = periodo;
       this.cdPed = cdPed;
       this.regCont = regCont;
       this.cdOp = cdOp;
       this.bimNeto = bimNeto;
       this.igv = igv;
       this.total = total;
       this.fecReg = fecReg;
       this.fecMod = fecMod;
       this.usuReg = usuReg;
       this.usuMod = usuMod;
       this.estado = estado;
       this.apscCotizacionDets = apscCotizacionDets;
    }
   
     @Id 

    
    @Column(name="ID_COTIZACION", unique=true, nullable=false)
    public long getIdCotizacion() {
        return this.idCotizacion;
    }
    
    public void setIdCotizacion(long idCotizacion) {
        this.idCotizacion = idCotizacion;
    }

    
    @Column(name="ID_CLIENTE")
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="ID_FORPAGO")
    public Long getIdForpago() {
        return this.idForpago;
    }
    
    public void setIdForpago(Long idForpago) {
        this.idForpago = idForpago;
    }

    
    @Column(name="ID_VEND")
    public Long getIdVend() {
        return this.idVend;
    }
    
    public void setIdVend(Long idVend) {
        this.idVend = idVend;
    }

    
    @Column(name="ID_ESTADO")
    public Long getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Long idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="ANIO", length=8)
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }

    
    @Column(name="PERIODO", length=8)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="CD_PED", length=16)
    public String getCdPed() {
        return this.cdPed;
    }
    
    public void setCdPed(String cdPed) {
        this.cdPed = cdPed;
    }

    
    @Column(name="REG_CONT", length=16)
    public String getRegCont() {
        return this.regCont;
    }
    
    public void setRegCont(String regCont) {
        this.regCont = regCont;
    }

    
    @Column(name="CD_OP", length=16)
    public String getCdOp() {
        return this.cdOp;
    }
    
    public void setCdOp(String cdOp) {
        this.cdOp = cdOp;
    }

    
    @Column(name="BIM_NETO", precision=18, scale=7)
    public BigDecimal getBimNeto() {
        return this.bimNeto;
    }
    
    public void setBimNeto(BigDecimal bimNeto) {
        this.bimNeto = bimNeto;
    }

    
    @Column(name="IGV", precision=18, scale=7)
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    
    @Column(name="TOTAL", precision=18, scale=7)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_REG", length=23)
    public Date getFecReg() {
        return this.fecReg;
    }
    
    public void setFecReg(Date fecReg) {
        this.fecReg = fecReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_MOD", length=23)
    public Date getFecMod() {
        return this.fecMod;
    }
    
    public void setFecMod(Date fecMod) {
        this.fecMod = fecMod;
    }

    
    @Column(name="USU_REG", length=16)
    public String getUsuReg() {
        return this.usuReg;
    }
    
    public void setUsuReg(String usuReg) {
        this.usuReg = usuReg;
    }

    
    @Column(name="USU_MOD", length=16)
    public String getUsuMod() {
        return this.usuMod;
    }
    
    public void setUsuMod(String usuMod) {
        this.usuMod = usuMod;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="apscCotizacion")
    public Set<ApscCotizacionDet> getApscCotizacionDets() {
        return this.apscCotizacionDets;
    }
    
    public void setApscCotizacionDets(Set<ApscCotizacionDet> apscCotizacionDets) {
        this.apscCotizacionDets = apscCotizacionDets;
    }




}


