package ferro.model;

// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * ApscPedido generated by hbm2java
 */
@Entity
@Table(name = "APSC_PEDIDO",schema="ERP"
/*"dbo"
,catalog="ERP"*/)
@DynamicUpdate
@DynamicInsert
@SelectBeforeUpdate
public class ApscPedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idPedido;
	private ApscForpago apscForpago;
	private ApscVendedor apscVendedor;
	private ApscCliente apscCliente;
	private ApscEstado apscEstado;
	private String anio;
	private String periodo;
	private String cdPed;
	private String regCont;
	private String cdOp;
	private BigDecimal bimNeto;
	private BigDecimal igv;
	private BigDecimal total;
	private String condPago;
	private String ciudad;
	private Date fecReg;
	private Date fecMod;
	private String usuReg;
	private String usuMod;
	private Boolean estado;
	private String obs;
	private Set<ApscAlarma> apscAlarmas = new HashSet<ApscAlarma>(0);
	private List<ApscPedidoDet> apscPedidoDets = new ArrayList<ApscPedidoDet>(0);
	private Set<ApscEstPorPedido> apscEstPorPedidos = new HashSet<ApscEstPorPedido>(0);

	public ApscPedido() {
	}

	public ApscPedido(long idPedido) {
		this.idPedido = idPedido;
	}

	public ApscPedido(long idPedido, ApscForpago apscForpago,
			ApscVendedor apscVendedor, ApscCliente apscCliente,
			ApscEstado apscEstado, String anio, String periodo, String cdPed,
			String regCont, String cdOp, BigDecimal bimNeto, BigDecimal igv,
			BigDecimal total, String condPago, String ciudad, Date fecReg,
			Date fecMod, String usuReg, String usuMod, Boolean estado,
			String obs, Set<ApscAlarma> apscAlarmas,
			List<ApscPedidoDet> apscPedidoDets,
			Set<ApscEstPorPedido> apscEstPorPedidos) {
		this.idPedido = idPedido;
		this.apscForpago = apscForpago;
		this.apscVendedor = apscVendedor;
		this.apscCliente = apscCliente;
		this.apscEstado = apscEstado;
		this.anio = anio;
		this.periodo = periodo;
		this.cdPed = cdPed;
		this.regCont = regCont;
		this.cdOp = cdOp;
		this.bimNeto = bimNeto;
		this.igv = igv;
		this.total = total;
		this.condPago = condPago;
		this.ciudad = ciudad;
		this.fecReg = fecReg;
		this.fecMod = fecMod;
		this.usuReg = usuReg;
		this.usuMod = usuMod;
		this.estado = estado;
		this.obs = obs;
		this.apscAlarmas = apscAlarmas;
		this.apscPedidoDets = apscPedidoDets;
		this.apscEstPorPedidos = apscEstPorPedidos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_PEDIDO", unique = true, nullable = false)
	public long getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(long idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FORPAGO")
	public ApscForpago getApscForpago() {
		return this.apscForpago;
	}

	public void setApscForpago(ApscForpago apscForpago) {
		this.apscForpago = apscForpago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VEND")
	public ApscVendedor getApscVendedor() {
		return this.apscVendedor;
	}

	public void setApscVendedor(ApscVendedor apscVendedor) {
		this.apscVendedor = apscVendedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE")
	public ApscCliente getApscCliente() {
		return this.apscCliente;
	}

	public void setApscCliente(ApscCliente apscCliente) {
		this.apscCliente = apscCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTADO")
	public ApscEstado getApscEstado() {
		return this.apscEstado;
	}

	public void setApscEstado(ApscEstado apscEstado) {
		this.apscEstado = apscEstado;
	}

	@Column(name = "ANIO", length = 8)
	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	@Column(name = "PERIODO", length = 8)
	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	@Column(name = "CD_PED", length = 16)
	public String getCdPed() {
		return this.cdPed;
	}

	public void setCdPed(String cdPed) {
		this.cdPed = cdPed;
	}

	@Column(name = "REG_CONT", length = 16)
	public String getRegCont() {
		return this.regCont;
	}

	public void setRegCont(String regCont) {
		this.regCont = regCont;
	}

	@Column(name = "CD_OP", length = 16)
	public String getCdOp() {
		return this.cdOp;
	}

	public void setCdOp(String cdOp) {
		this.cdOp = cdOp;
	}

	@Column(name = "BIM_NETO", precision = 18, scale = 7)
	public BigDecimal getBimNeto() {
		return this.bimNeto;
	}

	public void setBimNeto(BigDecimal bimNeto) {
		this.bimNeto = bimNeto;
	}

	@Column(name = "IGV", precision = 18, scale = 7)
	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	@Column(name = "TOTAL", precision = 18, scale = 7)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "COND_PAGO", length = 32)
	public String getCondPago() {
		return this.condPago;
	}

	public void setCondPago(String condPago) {
		this.condPago = condPago;
	}

	@Column(name = "CIUDAD", length = 32)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REG",insertable=false,updatable=false, length = 23 )
	public Date getFecReg() {
		return this.fecReg;
	}

	public void setFecReg(Date fecReg) {
		this.fecReg = fecReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MOD",insertable=false, length = 23)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "USU_REG", length = 16)
	public String getUsuReg() {
		return this.usuReg;
	}

	public void setUsuReg(String usuReg) {
		this.usuReg = usuReg;
	}

	@Column(name = "USU_MOD", length = 16)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "OBS",length = 1024)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apscPedido")
	public Set<ApscAlarma> getApscAlarmas() {
		return this.apscAlarmas;
	}

	public void setApscAlarmas(Set<ApscAlarma> apscAlarmas) {
		this.apscAlarmas = apscAlarmas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apscPedido")
	public List<ApscPedidoDet> getApscPedidoDets() {
		return this.apscPedidoDets;
	}

	public void setApscPedidoDets(List<ApscPedidoDet> apscPedidoDets) {
		this.apscPedidoDets = apscPedidoDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apscPedido")
	public Set<ApscEstPorPedido> getApscEstPorPedidos() {
		return this.apscEstPorPedidos;
	}

	public void setApscEstPorPedidos(Set<ApscEstPorPedido> apscEstPorPedidos) {
		this.apscEstPorPedidos = apscEstPorPedidos;
	}

}