package ferro.model;
// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApscEstPorPedido generated by hbm2java
 */
@Entity
@Table(name="APSC_EST_POR_PEDIDO"
,schema="ERP"
/*"dbo"
,catalog="ERP"*/
)
public class ApscEstPorPedido  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idEstPed;
     private ApscPedido apscPedido;
     private Integer idEstado;
     private String usuReg;
     private Date fecReg;
     private Date fecMod;
     private Boolean estado;

    public ApscEstPorPedido() {
    }

	
    public ApscEstPorPedido(long idEstPed) {
        this.idEstPed = idEstPed;
    }
    public ApscEstPorPedido(long idEstPed, ApscPedido apscPedido, Integer idEstado, String usuReg, Date fecReg, Date fecMod, Boolean estado) {
       this.idEstPed = idEstPed;
       this.apscPedido = apscPedido;
       this.idEstado = idEstado;
       this.usuReg = usuReg;
       this.fecReg = fecReg;
       this.fecMod = fecMod;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="ID_EST_PED", unique=true, nullable=false)
    public long getIdEstPed() {
        return this.idEstPed;
    }
    
    public void setIdEstPed(long idEstPed) {
        this.idEstPed = idEstPed;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PEDIDO")
    public ApscPedido getApscPedido() {
        return this.apscPedido;
    }
    
    public void setApscPedido(ApscPedido apscPedido) {
        this.apscPedido = apscPedido;
    }

    
    @Column(name="ID_ESTADO")
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="USU_REG", length=16)
    public String getUsuReg() {
        return this.usuReg;
    }
    
    public void setUsuReg(String usuReg) {
        this.usuReg = usuReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_REG", length=23)
    public Date getFecReg() {
        return this.fecReg;
    }
    
    public void setFecReg(Date fecReg) {
        this.fecReg = fecReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_MOD", length=23)
    public Date getFecMod() {
        return this.fecMod;
    }
    
    public void setFecMod(Date fecMod) {
        this.fecMod = fecMod;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


