package ferro.model;
// Generated 17/03/2015 01:50:11 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApscProdCompro generated by hbm2java
 */
@Entity
@Table(name="APSC_PROD_COMPRO"
,schema="ERP"
/*"dbo"
,catalog="ERP"*/
)
public class ApscProdCompro  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idProdComp;
     private ApscVendedor apscVendedor;
     private Long idPedido;
     private String idProd;
     private String codComer;
     private BigDecimal cant;
     private BigDecimal precio;
     private BigDecimal dscto;
     private Date fecReg;
     private Date fecMod;
     private String usuReg;
     private String usuMod;
     private Boolean estado;

    public ApscProdCompro() {
    }

	
    public ApscProdCompro(long idProdComp) {
        this.idProdComp = idProdComp;
    }
    public ApscProdCompro(long idProdComp, ApscVendedor apscVendedor, Long idPedido, String idProd, String codComer, BigDecimal cant, BigDecimal precio, BigDecimal dscto, Date fecReg, Date fecMod, String usuReg, String usuMod, Boolean estado) {
       this.idProdComp = idProdComp;
       this.apscVendedor = apscVendedor;
       this.idPedido = idPedido;
       this.idProd = idProd;
       this.codComer = codComer;
       this.cant = cant;
       this.precio = precio;
       this.dscto = dscto;
       this.fecReg = fecReg;
       this.fecMod = fecMod;
       this.usuReg = usuReg;
       this.usuMod = usuMod;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="ID_PROD_COMP", unique=true, nullable=false)
    public long getIdProdComp() {
        return this.idProdComp;
    }
    
    public void setIdProdComp(long idProdComp) {
        this.idProdComp = idProdComp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_VEND")
    public ApscVendedor getApscVendedor() {
        return this.apscVendedor;
    }
    
    public void setApscVendedor(ApscVendedor apscVendedor) {
        this.apscVendedor = apscVendedor;
    }

    
    @Column(name="ID_PEDIDO")
    public Long getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Long idPedido) {
        this.idPedido = idPedido;
    }

    
    @Column(name="ID_PROD", length=16)
    public String getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(String idProd) {
        this.idProd = idProd;
    }

    
    @Column(name="COD_COMER", length=16)
    public String getCodComer() {
        return this.codComer;
    }
    
    public void setCodComer(String codComer) {
        this.codComer = codComer;
    }

    
    @Column(name="CANT", precision=18, scale=7)
    public BigDecimal getCant() {
        return this.cant;
    }
    
    public void setCant(BigDecimal cant) {
        this.cant = cant;
    }

    
    @Column(name="PRECIO", precision=18, scale=7)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="DSCTO", precision=18, scale=7)
    public BigDecimal getDscto() {
        return this.dscto;
    }
    
    public void setDscto(BigDecimal dscto) {
        this.dscto = dscto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_REG", length=23)
    public Date getFecReg() {
        return this.fecReg;
    }
    
    public void setFecReg(Date fecReg) {
        this.fecReg = fecReg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_MOD", length=23)
    public Date getFecMod() {
        return this.fecMod;
    }
    
    public void setFecMod(Date fecMod) {
        this.fecMod = fecMod;
    }

    
    @Column(name="USU_REG", length=16)
    public String getUsuReg() {
        return this.usuReg;
    }
    
    public void setUsuReg(String usuReg) {
        this.usuReg = usuReg;
    }

    
    @Column(name="USU_MOD", length=16)
    public String getUsuMod() {
        return this.usuMod;
    }
    
    public void setUsuMod(String usuMod) {
        this.usuMod = usuMod;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


