package ferro.model;

// Generated 09/02/2015 04:25:04 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * ApscParamGenerales generated by hbm2java
 */
@Entity
@Table(name = "APSC_PARAM_GENERALES",schema="ERP"
/*"dbo"
,catalog="ERP"*/)
//@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true, selectBeforeUpdate = true)
@DynamicUpdate
@DynamicInsert
@SelectBeforeUpdate 
public class ApscParamGenerales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idParam;
	private String desParam;
	private String valParam;
	private String codParam;
	private String desCate;
	private String codCate;
	private Date fecReg;
	private Date fecMod;
	private String usuReg;
	private String usuMod;
	private Boolean estado;

	public ApscParamGenerales() {
	}

	public ApscParamGenerales(long idParam) {
		this.idParam = idParam;
	}

	public ApscParamGenerales(long idParam, String desParam, String valParam,
			String codParam, String desCate, String codCate, Date fecReg,
			Date fecMod, String usuReg, String usuMod, Boolean estado) {
		this.idParam = idParam;
		this.desParam = desParam;
		this.valParam = valParam;
		this.codParam = codParam;
		this.desCate = desCate;
		this.codCate = codCate;
		this.fecReg = fecReg;
		this.fecMod = fecMod;
		this.usuReg = usuReg;
		this.usuMod = usuMod;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_PARAM", unique = true, nullable = false)
	public long getIdParam() {
		return this.idParam;
	}

	public void setIdParam(long idParam) {
		this.idParam = idParam;
	}

	@Column(name = "DES_PARAM", length = 32)
	public String getDesParam() {
		return this.desParam;
	}

	public void setDesParam(String desParam) {
		this.desParam = desParam;
	}

	@Column(name = "VAL_PARAM", length = 256)
	public String getValParam() {
		return this.valParam;
	}

	public void setValParam(String valParam) {
		this.valParam = valParam;
	}

	@Column(name = "COD_PARAM", length = 32)
	public String getCodParam() {
		return this.codParam;
	}

	public void setCodParam(String codParam) {
		this.codParam = codParam;
	}

	@Column(name = "DES_CATE", length = 32)
	public String getDesCate() {
		return this.desCate;
	}

	public void setDesCate(String desCate) {
		this.desCate = desCate;
	}

	@Column(name = "COD_CATE", length = 32)
	public String getCodCate() {
		return this.codCate;
	}

	public void setCodCate(String codCate) {
		this.codCate = codCate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REG",insertable = false, length = 23)
	public Date getFecReg() {
		return this.fecReg;
	}

	public void setFecReg(Date fecReg) {
		this.fecReg = fecReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MOD", length = 23)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "USU_REG", length = 16)
	public String getUsuReg() {
		return this.usuReg;
	}

	public void setUsuReg(String usuReg) {
		this.usuReg = usuReg;
	}

	@Column(name = "USU_MOD", length = 16)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "ESTADO",insertable = false)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
