package ferro.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ApscUsuarios generated by hbm2java
 * , UserDetails
 */
@Entity
@Table(name = "APSC_USUARIOS",schema="ERP"
/*"dbo"
,catalog="ERP"*/)
public class ApscUsuarios implements java.io.Serializable
//, UserDetails
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUser;
	private ApscPerfil apscPerfil;
	private String userIn;
	private String passwordIn;
	private String nomUser;
	private String apePat;
	private String apeMat;
	private String numCel;
	private Date fecReg;
	private Date fecMod;
	private String usuReg;
	private String usuMod;
	private Boolean estado;

	public ApscUsuarios() {
	}

	public ApscUsuarios(int idUser) {
		this.idUser = idUser;
	}

	public ApscUsuarios(int idUser, ApscPerfil apscPerfil, String userIn,
			String passwordIn, String nomUser, String apePat, String apeMat,
			String numCel, Date fecReg, Date fecMod, String usuReg,
			String usuMod, Boolean estado) {
		this.idUser = idUser;
		this.apscPerfil = apscPerfil;
		this.userIn = userIn;
		this.passwordIn = passwordIn;
		this.nomUser = nomUser;
		this.apePat = apePat;
		this.apeMat = apeMat;
		this.numCel = numCel;
		this.fecReg = fecReg;
		this.fecMod = fecMod;
		this.usuReg = usuReg;
		this.usuMod = usuMod;
		this.estado = estado;
	}

	@Id
	@Column(name = "ID_USER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL")
	public ApscPerfil getApscPerfil() {
		return this.apscPerfil;
	}

	public void setApscPerfil(ApscPerfil apscPerfil) {
		this.apscPerfil = apscPerfil;
	}

	@Column(name = "USER_IN", length = 16)
	public String getUserIn() {
		return this.userIn;
	}

	public void setUserIn(String userIn) {
		this.userIn = userIn;
	}

	@Column(name = "PASSWORD_IN", length = 16)
	public String getPasswordIn() {
		return this.passwordIn;
	}

	public void setPasswordIn(String passwordIn) {
		this.passwordIn = passwordIn;
	}

	@Column(name = "NOM_USER", length = 32)
	public String getNomUser() {
		return this.nomUser;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}

	@Column(name = "APE_PAT", length = 32)
	public String getApePat() {
		return this.apePat;
	}

	public void setApePat(String apePat) {
		this.apePat = apePat;
	}

	@Column(name = "APE_MAT", length = 32)
	public String getApeMat() {
		return this.apeMat;
	}

	public void setApeMat(String apeMat) {
		this.apeMat = apeMat;
	}

	@Column(name = "NUM_CEL", length = 16)
	public String getNumCel() {
		return this.numCel;
	}

	public void setNumCel(String numCel) {
		this.numCel = numCel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REG", length = 23)
	public Date getFecReg() {
		return this.fecReg;
	}

	public void setFecReg(Date fecReg) {
		this.fecReg = fecReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MOD", length = 23)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "USU_REG", length = 16)
	public String getUsuReg() {
		return this.usuReg;
	}

	public void setUsuReg(String usuReg) {
		this.usuReg = usuReg;
	}

	@Column(name = "USU_MOD", length = 16)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	/*@Transient
	public Collection<? extends GrantedAuthority> getAuthorities() {
		Collection<GrantedAuthority> authorities = new ArrayList<GrantedAuthority>();
		authorities.add(new SimpleGrantedAuthority(this.getApscPerfil().getDescripcion()));
		return authorities;
	}

	@Transient
	public String getPassword() {

		return getPasswordIn();
	}

	@Transient
	public String getUsername() {

		return getUserIn();
	}

	@Transient
	public boolean isAccountNonExpired() {
		return false;
	}

	@Transient
	public boolean isAccountNonLocked() {
		return false;
	}

	@Transient
	public boolean isCredentialsNonExpired() {
		return false;
	}

	@Transient
	public boolean isEnabled() {
		return false;
	}*/
	@Transient
	public String getNomCompleto(){
		return getApePat()+" "+getApeMat()+","+getNomUser();
	}

}
